baseURL: "https://hannaabiakl.org/" 
title: Hanna Abi Akl
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: About
          url: /about/
          weight: 1
        - name: Publications
          url: /publications/
          weight: 2
        - name: Awards
          url: /awards/
          weight: 3
        - name: Projects, Software & Data
          url: /projects/
          weight: 4
        - name: Teaching
          url: /teaching/
          weight: 5
        - name: Community Service
          url: /community/
          weight: 6

params:
    description: "I am a scientist, author and researcher in logic, language, computation and neuro-symbolic artificial intelligence. My main areas of research are mapping language to symbolic structures, logic-based reasoning and graph-based knowledge representation methods in AI. I work as an AI & NLP Researcher and teach at Data ScienceTech Institute. I also enjoy writing poetry and novels."
    author: Hanna Abi Akl
    googleAnalyticsID: "G-97G4MZ4061"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Hanna Abi Akl
          subtitle: "I am a scientist, author and researcher in logic, language, computation and neuro-symbolic artificial intelligence. My main areas of research are mapping language to symbolic structures, logic-based reasoning and graph-based knowledge representation methods in AI. I work as an AI & NLP Researcher and teach at Data ScienceTech Institute. I also enjoy writing poetry and novels."
          imageUrl: "/picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Hanna Abi Akl
          buttons:
            - name: About
              url: /about/
            - name: Publications
              url: /publications/
            - name: Awards
              url: /awards/
            - name: Projects, Software & Data
              url: /projects/
            - name: Teaching
              url: /teaching/
            - name: Community Service
              url: /community/

    socialIcons:
        - name: CV
          url: /cv.pdf
        - name: Email
          url: mailto:hannaabiakl8@gmail.com
        - name: Location
          url: /location/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=7oVvfP4AAAAJ&hl=en&oi=ao
        - name: LinkedIn
          url: https://www.linkedin.com/in/hannaabiakl/
        - name: GitHub
          url: https://github.com/HannaAbiAkl?tab=repositories

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Hanna Abi Akl"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
